spring.application.name=tpejemplo

# Base de datos H2 en memoria
spring.datasource.url=jdbc:h2:mem:tpdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# Consola H2 (solo desarrollo)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Puerto
server.port=8080

# JWT
jwt.secret=clave-super-secreta-de-al-menos-32-caracteres-uade2026
jwt.expiration-ms=86400000
